# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lab1/lab1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1 || ORIG_REF_NAME==lab1}]

# IP: bd/lab1/ip/lab1_processing_system7_0_0/lab1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab1_processing_system7_0_0 || ORIG_REF_NAME==lab1_processing_system7_0_0}]

# XDC: bd/lab1/lab1_ooc.xdc
